# Generated by Django 5.1.4 on 2024-12-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('system_name', models.TextField()),
                ('project_name', models.TextField()),
                ('sample_prefix', models.TextField()),
                ('sample_number', models.IntegerField()),
                ('sample_suffix', models.TextField()),
                ('sample_type', models.TextField()),
                ('sample_name', models.TextField()),
                ('sample_set_id', models.IntegerField()),
                ('sample_set_name', models.TextField()),
                ('date_acquired', models.TextField()),
                ('acquired_by', models.TextField()),
                ('run_time', models.TextField()),
                ('processing_method', models.TextField()),
                ('processed_channel_description', models.TextField()),
                ('injection_volume', models.TextField()),
                ('injection_id', models.IntegerField()),
                ('column_name', models.TextField()),
                ('column_serial_number', models.TextField()),
                ('instrument_method_id', models.IntegerField()),
                ('instrument_method_name', models.TextField()),
            ],
            options={
                'db_table': 'sample_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
