# Generated by Django 5.1.4 on 2024-12-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChromMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('system_name', models.TextField()),
                ('sample_name', models.TextField(blank=True, null=True)),
                ('sample_set_name', models.TextField(blank=True, null=True)),
                ('sample_set_id', models.IntegerField(blank=True, null=True)),
                ('channel_1', models.TextField(blank=True, null=True)),
                ('channel_2', models.TextField(blank=True, null=True)),
                ('channel_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chrom_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_type', models.IntegerField(blank=True, null=True)),
                ('new_column_1', models.IntegerField(blank=True, null=True)),
                ('new_column_2', models.IntegerField(blank=True, null=True)),
                ('new_column_3', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeakResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('channel_name', models.TextField(blank=True, null=True)),
                ('peak_name', models.TextField(blank=True, null=True)),
                ('peak_retention_time', models.FloatField(blank=True, null=True)),
                ('peak_start_time', models.FloatField(blank=True, null=True)),
                ('peak_end_time', models.FloatField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('percent_area', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('asym_at_10', models.FloatField(blank=True, null=True)),
                ('plate_count', models.FloatField(blank=True, null=True)),
                ('res_hh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peak_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectID',
            fields=[
                ('project_name', models.TextField(blank=True, null=True)),
                ('sip_number', models.TextField(blank=True, null=True)),
                ('clone_id', models.TextField(blank=True, null=True)),
                ('sample_name', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('analyst', models.TextField(blank=True, null=True)),
                ('harvest_date', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('analysis_type', models.TextField(blank=True, null=True)),
                ('sample_type', models.TextField(blank=True, null=True)),
                ('selected_samples', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportInstance',
            fields=[
                ('report_instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('exclusions', models.TextField(blank=True, null=True)),
                ('report_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('system_name', models.TextField(blank=True, null=True)),
                ('project_name', models.IntegerField(blank=True, null=True)),
                ('sample_set_id', models.IntegerField(blank=True, null=True)),
                ('sample_set_name', models.TextField(blank=True, null=True)),
                ('acquired_by', models.TextField(blank=True, null=True)),
                ('column_serial_number', models.TextField(blank=True, null=True)),
                ('new_column', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SampleMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('system_name', models.TextField()),
                ('project_name', models.TextField(blank=True, null=True)),
                ('sample_prefix', models.TextField(blank=True, null=True)),
                ('sample_number', models.IntegerField(blank=True, null=True)),
                ('sample_suffix', models.TextField(blank=True, null=True)),
                ('sample_type', models.TextField(blank=True, null=True)),
                ('sample_name', models.TextField(blank=True, null=True)),
                ('sample_set_id', models.IntegerField(blank=True, null=True)),
                ('sample_set_name', models.TextField(blank=True, null=True)),
                ('date_acquired', models.DateField(blank=True, null=True)),
                ('acquired_by', models.TextField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
                ('processing_method', models.TextField(blank=True, null=True)),
                ('processed_channel_description', models.TextField(blank=True, null=True)),
                ('injection_volume', models.FloatField(blank=True, null=True)),
                ('injection_id', models.IntegerField(blank=True, null=True)),
                ('column_name', models.TextField(blank=True, null=True)),
                ('column_serial_number', models.TextField(blank=True, null=True)),
                ('instrument_method_id', models.IntegerField(blank=True, null=True)),
                ('instrument_method_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sample_metadata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('system_name', models.TextField(primary_key=True, serialize=False)),
                ('channel_1', models.TextField(blank=True, null=True)),
                ('channel_2', models.TextField(blank=True, null=True)),
                ('channel_3', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'system_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('system_name', models.TextField()),
                ('time', models.FloatField()),
                ('channel_1', models.FloatField(blank=True, null=True)),
                ('channel_2', models.FloatField(blank=True, null=True)),
                ('channel_3', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_series_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField()),
                ('user_name', models.TextField(primary_key=True, serialize=False)),
                ('user_initials', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
