# Generated by Django 5.1.4 on 2025-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectid',
            old_name='sample_name',
            new_name='fb_id',
        ),
        migrations.RemoveField(
            model_name='projectid',
            name='clone_id',
        ),
        migrations.RemoveField(
            model_name='projectid',
            name='project_name',
        ),
        migrations.AddField(
            model_name='empowercolumnlogbook',
            name='most_recent_injection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='cld_30ml_octet_titer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='column_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='fast_pro_a_recovery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='hccf_loading_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='intact_or_reduced',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='mass_confirmed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='pro_aqa_titer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='proa_column_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='proa_eluate_a280_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='proa_eluate_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='proa_recovery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='purification_recovery_a280',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='sample_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='sec_2_wks_a_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='sec_2wks_n_conc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='titer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectid',
            name='unifi_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
