# Generated by Django 5.1.4 on 2025-03-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0002_rename_sample_name_projectid_fb_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectID',
        ),
    ]
