create table sartoflow_time_series_data
(
    id                integer      not null
        primary key autoincrement,
    batch_id          varchar(255) not null,
    pdat_time         datetime     not null,
    process_time      real,
    ag2100_value      real,
    ag2100_setpoint   real,
    ag2100_mode       integer,
    ag2100_output     real,
    dpress_value      real,
    dpress_output     real,
    dpress_mode       integer,
    dpress_setpoint   real,
    f_perm_value      real,
    p2500_setpoint    real,
    p2500_value       real,
    p2500_output      real,
    p2500_mode        integer,
    p3000_setpoint    real,
    p3000_mode        integer,
    p3000_output      real,
    p3000_value       real,
    p3000_t           real,
    pir2600           real,
    pir2700           real,
    pirc2500_value    real,
    pirc2500_output   real,
    pirc2500_setpoint real,
    pirc2500_mode     integer,
    qir2000           real,
    qir2100           real,
    tir2100           real,
    tmp               real,
    wir2700           real,
    wirc2100_output   real,
    wirc2100_setpoint real,
    wirc2100_mode     integer
);

