# Generated by Django 5.1.4 on 2025-02-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samplemetadata',
            options={'managed': True},
        ),
    ]
