# Generated by Django 5.1.4 on 2025-02-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktaresult',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
