# Generated by Django 5.1.4 on 2025-02-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0002_alter_aktaresult_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='date_acquired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
