# Generated by Django 5.1.4 on 2025-02-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0003_alter_samplemetadata_date_acquired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinformation',
            name='protein',
            field=models.TextField(blank=True, null=True),
        ),
    ]
