# Generated by Django 5.1.4 on 2025-02-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0005_report_selected_result_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_created',
            field=models.TextField(blank=True, null=True),
        ),
    ]
