# Generated by Django 5.1.4 on 2025-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0006_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
