# Generated by Django 5.1.4 on 2025-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0007_report_selected_result_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.TextField()),
                ('project', models.TextField()),
                ('project_description', models.TextField(blank=True, null=True)),
                ('molecule_type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purifications', models.TextField(blank=True, null=True)),
                ('plasmids', models.TextField(blank=True, null=True)),
                ('plasmid_description', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('transfections', models.TextField(blank=True, null=True)),
                ('titer', models.FloatField(blank=True, null=True)),
                ('protein_concentration', models.FloatField(blank=True, null=True)),
                ('nanodrop_e1', models.FloatField(blank=True, null=True)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('percent_poi', models.FloatField(blank=True, null=True)),
                ('pi', models.FloatField(blank=True, null=True)),
                ('latest_purification_date', models.DateField(blank=True, null=True)),
                ('purified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'project_information',
                'managed': True,
            },
        ),
    ]
