# Generated by Django 5.1.4 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0007_alter_report_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectid',
            name='cell_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
