# Generated by Django 5.1.4 on 2025-02-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0008_projectinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SartoflowTimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=255)),
                ('pdat_time', models.DateTimeField()),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('ag2100_value', models.FloatField(blank=True, null=True)),
                ('ag2100_setpoint', models.FloatField(blank=True, null=True)),
                ('ag2100_mode', models.IntegerField(blank=True, null=True)),
                ('ag2100_output', models.FloatField(blank=True, null=True)),
                ('dpress_value', models.FloatField(blank=True, null=True)),
                ('dpress_output', models.FloatField(blank=True, null=True)),
                ('dpress_mode', models.IntegerField(blank=True, null=True)),
                ('dpress_setpoint', models.FloatField(blank=True, null=True)),
                ('f_perm_value', models.FloatField(blank=True, null=True)),
                ('p2500_setpoint', models.FloatField(blank=True, null=True)),
                ('p2500_value', models.FloatField(blank=True, null=True)),
                ('p2500_output', models.FloatField(blank=True, null=True)),
                ('p2500_mode', models.IntegerField(blank=True, null=True)),
                ('p3000_setpoint', models.FloatField(blank=True, null=True)),
                ('p3000_mode', models.IntegerField(blank=True, null=True)),
                ('p3000_output', models.FloatField(blank=True, null=True)),
                ('p3000_value', models.FloatField(blank=True, null=True)),
                ('p3000_t', models.FloatField(blank=True, null=True)),
                ('pir2600', models.FloatField(blank=True, null=True)),
                ('pir2700', models.FloatField(blank=True, null=True)),
                ('pirc2500_value', models.FloatField(blank=True, null=True)),
                ('pirc2500_output', models.FloatField(blank=True, null=True)),
                ('pirc2500_setpoint', models.FloatField(blank=True, null=True)),
                ('pirc2500_mode', models.IntegerField(blank=True, null=True)),
                ('qir2000', models.FloatField(blank=True, null=True)),
                ('qir2100', models.FloatField(blank=True, null=True)),
                ('tir2100', models.FloatField(blank=True, null=True)),
                ('tmp', models.FloatField(blank=True, null=True)),
                ('wir2700', models.FloatField(blank=True, null=True)),
                ('wirc2100_output', models.FloatField(blank=True, null=True)),
                ('wirc2100_setpoint', models.FloatField(blank=True, null=True)),
                ('wirc2100_mode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sartoflow_time_series_data',
            },
        ),
    ]
