# Generated by Django 5.1.4 on 2025-03-04 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0008_projectid_cell_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFDFMetadata',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('molecule_name', models.TextField()),
                ('experiment_name', models.TextField()),
                ('experimental_notes', models.TextField(blank=True, null=True)),
                ('cassette_type', models.TextField()),
                ('load_concentration', models.FloatField()),
                ('load_volume', models.FloatField()),
                ('load_mass', models.FloatField()),
                ('system_void_volume', models.FloatField()),
                ('target_diafiltration_concentration', models.FloatField()),
                ('uf1_target_reservoir_mass', models.FloatField()),
                ('diavolumes', models.IntegerField()),
                ('permeate_target_mass', models.FloatField()),
                ('diafiltration_volume_required', models.FloatField()),
                ('lmh_target', models.FloatField()),
                ('flow_rate', models.FloatField()),
                ('target_flow_rate', models.FloatField()),
                ('target_p2500_setpoint', models.FloatField()),
                ('target_p3000_setpoint', models.FloatField()),
                ('recovery', models.FloatField()),
                ('final_volume', models.FloatField()),
                ('final_concentration', models.FloatField()),
                ('product_mass', models.FloatField()),
                ('yield_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ufdf_metadata',
            },
        ),
        migrations.AlterField(
            model_name='sartoflowtimeseriesdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='sartoflowtimeseriesdata',
            name='result_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.ufdfmetadata'),
        ),
    ]
