# Generated by Django 5.1.4 on 2025-03-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0009_ufdfmetadata_alter_sartoflowtimeseriesdata_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SartoflowTimeSeriesData',
        ),
        migrations.DeleteModel(
            name='UFDFMetadata',
        ),
    ]
