# Generated by Django 5.1.4 on 2025-02-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0009_sartoflowtimeseriesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktaColumnsCharacteristics',
            fields=[
                ('column_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('column_type', models.CharField(max_length=255)),
                ('technique', models.CharField(max_length=255)),
                ('column_volume', models.FloatField()),
                ('diameter', models.FloatField()),
                ('bed_height', models.FloatField()),
                ('resin', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('asymmetry', models.FloatField()),
                ('plates_per_meter', models.FloatField()),
                ('HETP', models.FloatField()),
                ('num_cycles', models.BigIntegerField()),
                ('avg_starting_pressure', models.FloatField()),
            ],
            options={
                'db_table': 'akta_columns_characteristics',
            },
        ),
        migrations.CreateModel(
            name='AktaMethodInformation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=255)),
                ('last_saved', models.DateTimeField()),
                ('created_by_user', models.CharField(max_length=255)),
                ('method_notes', models.TextField()),
                ('result_name', models.CharField(max_length=255)),
                ('start_notes', models.TextField()),
                ('scouting', models.BigIntegerField()),
                ('created_for_system', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'akta_method_information',
            },
        ),
        migrations.CreateModel(
            name='AktaRawData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('time', models.FloatField()),
                ('uv_001', models.FloatField()),
                ('uv_002', models.FloatField()),
                ('uv_003', models.FloatField()),
                ('cond', models.FloatField()),
                ('ConcB', models.BigIntegerField()),
                ('pH', models.BigIntegerField()),
                ('system_flow', models.FloatField()),
                ('sample_flow', models.FloatField()),
                ('column_11', models.BigIntegerField()),
                ('column_12', models.BigIntegerField()),
                ('column_13', models.BigIntegerField()),
            ],
            options={
                'db_table': 'akta_raw_data',
            },
        ),
        migrations.CreateModel(
            name='AktaResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('column_id', models.BigIntegerField(blank=True, null=True)),
                ('method_id', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('user', models.CharField(max_length=255)),
                ('sample_id', models.CharField(max_length=255)),
                ('run_type', models.BigIntegerField()),
                ('scouting_id', models.BigIntegerField()),
                ('scouting_run_num', models.BigIntegerField()),
                ('group_id', models.BigIntegerField()),
                ('run_on_system', models.CharField(max_length=255)),
                ('run_log_id', models.BigIntegerField()),
                ('source_material_id', models.BigIntegerField()),
                ('downstream_step_id', models.BigIntegerField()),
                ('text_instruction_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'akta_result',
            },
        ),
        migrations.CreateModel(
            name='AktaScoutingList',
            fields=[
                ('scouting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_num_of_scoutings', models.BigIntegerField()),
                ('run_scouting', models.BigIntegerField()),
                ('run', models.BigIntegerField()),
                ('scouting', models.BooleanField()),
                ('variable', models.TextField()),
                ('block', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'akta_scouting_list',
            },
        ),
        migrations.CreateModel(
            name='DnAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('study_name', models.CharField(max_length=255)),
                ('description_of_purpose', models.TextField()),
                ('load_volume', models.FloatField()),
                ('notes', models.TextField()),
            ],
            options={
                'db_table': 'dn_assignment',
            },
        ),
        migrations.CreateModel(
            name='PDSamples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.IntegerField()),
                ('pd_number', models.CharField(max_length=255)),
                ('sample_volume_ul', models.FloatField()),
                ('identifier', models.CharField(max_length=255)),
                ('description_volume', models.TextField()),
                ('a280_date', models.DateField(blank=True, null=True)),
                ('concentration_mg_ml', models.FloatField(blank=True, null=True)),
                ('sec_date', models.DateField(blank=True, null=True)),
                ('hmw_percentage', models.FloatField(blank=True, null=True)),
                ('mp_percentage', models.FloatField(blank=True, null=True)),
                ('lmw_percentage', models.FloatField(blank=True, null=True)),
                ('sec_total_area', models.FloatField(blank=True, null=True)),
                ('sec_injection_ug', models.FloatField(blank=True, null=True)),
                ('sec_dilution', models.FloatField(blank=True, null=True)),
                ('sec_load_volume_ul', models.FloatField(blank=True, null=True)),
                ('hplc_proa_titer_mg_ml', models.FloatField(blank=True, null=True)),
                ('hcp_ppm', models.FloatField(blank=True, null=True)),
                ('proa_ppm', models.FloatField(blank=True, null=True)),
                ('dna_ppm', models.FloatField(blank=True, null=True)),
                ('akta_fraction_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'pd_samples',
            },
        ),
    ]
