# Generated by Django 5.1.4 on 2025-03-04 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0010_delete_sartoflowtimeseriesdata_delete_ufdfmetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UFDFMetadata',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('molecule_name', models.TextField()),
                ('experiment_name', models.TextField()),
                ('experimental_notes', models.TextField(blank=True, null=True)),
                ('cassette_type', models.TextField()),
                ('load_concentration', models.FloatField()),
                ('load_volume', models.FloatField()),
                ('load_mass', models.FloatField()),
                ('system_void_volume', models.FloatField()),
                ('target_diafiltration_concentration', models.FloatField()),
                ('uf1_target_reservoir_mass', models.FloatField()),
                ('diavolumes', models.IntegerField()),
                ('permeate_target_mass', models.FloatField()),
                ('diafiltration_volume_required', models.FloatField()),
                ('lmh_target', models.FloatField()),
                ('flow_rate', models.FloatField()),
                ('target_flow_rate', models.FloatField()),
                ('target_p2500_setpoint', models.FloatField()),
                ('target_p3000_setpoint', models.FloatField()),
                ('recovery', models.FloatField()),
                ('final_volume', models.FloatField()),
                ('final_concentration', models.FloatField()),
                ('product_mass', models.FloatField()),
                ('yield_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ufdf_metadata',
            },
        ),
        migrations.CreateModel(
            name='SartoflowTimeSeriesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('batch_id', models.CharField(max_length=255)),
                ('pdat_time', models.DateTimeField()),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('ag2100_value', models.FloatField(blank=True, null=True)),
                ('ag2100_setpoint', models.FloatField(blank=True, null=True)),
                ('ag2100_mode', models.IntegerField(blank=True, null=True)),
                ('ag2100_output', models.FloatField(blank=True, null=True)),
                ('dpress_value', models.FloatField(blank=True, null=True)),
                ('dpress_output', models.FloatField(blank=True, null=True)),
                ('dpress_mode', models.IntegerField(blank=True, null=True)),
                ('dpress_setpoint', models.FloatField(blank=True, null=True)),
                ('f_perm_value', models.FloatField(blank=True, null=True)),
                ('p2500_setpoint', models.FloatField(blank=True, null=True)),
                ('p2500_value', models.FloatField(blank=True, null=True)),
                ('p2500_output', models.FloatField(blank=True, null=True)),
                ('p2500_mode', models.IntegerField(blank=True, null=True)),
                ('p3000_setpoint', models.FloatField(blank=True, null=True)),
                ('p3000_mode', models.IntegerField(blank=True, null=True)),
                ('p3000_output', models.FloatField(blank=True, null=True)),
                ('p3000_value', models.FloatField(blank=True, null=True)),
                ('p3000_t', models.FloatField(blank=True, null=True)),
                ('pir2600', models.FloatField(blank=True, null=True)),
                ('pir2700', models.FloatField(blank=True, null=True)),
                ('pirc2500_value', models.FloatField(blank=True, null=True)),
                ('pirc2500_output', models.FloatField(blank=True, null=True)),
                ('pirc2500_setpoint', models.FloatField(blank=True, null=True)),
                ('pirc2500_mode', models.IntegerField(blank=True, null=True)),
                ('qir2000', models.FloatField(blank=True, null=True)),
                ('qir2100', models.FloatField(blank=True, null=True)),
                ('tir2100', models.FloatField(blank=True, null=True)),
                ('tmp', models.FloatField(blank=True, null=True)),
                ('wir2700', models.FloatField(blank=True, null=True)),
                ('wirc2100_output', models.FloatField(blank=True, null=True)),
                ('wirc2100_setpoint', models.FloatField(blank=True, null=True)),
                ('wirc2100_mode', models.IntegerField(blank=True, null=True)),
                ('result_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.ufdfmetadata')),
            ],
            options={
                'db_table': 'sartoflow_time_series_data',
                'managed': True,
            },
        ),
    ]
