# Generated by Django 5.1.4 on 2025-02-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0010_aktacolumnscharacteristics_aktamethodinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktaChromatogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml', models.FloatField()),
                ('uv_1_280', models.FloatField()),
                ('uv_2_0', models.FloatField(blank=True, null=True)),
                ('uv_3_0', models.FloatField(blank=True, null=True)),
                ('cond', models.FloatField()),
                ('conc_b', models.FloatField()),
                ('pH', models.FloatField(blank=True, null=True)),
                ('system_flow', models.FloatField(blank=True, null=True)),
                ('system_linear_flow', models.FloatField(blank=True, null=True)),
                ('system_pressure', models.FloatField(blank=True, null=True)),
                ('cond_temp', models.FloatField(blank=True, null=True)),
                ('sample_flow', models.FloatField(blank=True, null=True)),
                ('sample_linear_flow', models.FloatField(blank=True, null=True)),
                ('sample_pressure', models.FloatField(blank=True, null=True)),
                ('preC_pressure', models.FloatField(blank=True, null=True)),
                ('deltaC_pressure', models.FloatField(blank=True, null=True)),
                ('postC_pressure', models.FloatField(blank=True, null=True)),
                ('frac_temp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'akta_chromatogram',
            },
        ),
    ]
