# Generated by Django 5.1.4 on 2025-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0011_ufdfmetadata_sartoflowtimeseriesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='system_void_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
