# Generated by Django 5.1.4 on 2025-02-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0012_aktafraction_aktarunlog_delete_aktarawdata_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aktafraction',
            table='akta_fraction',
        ),
        migrations.AlterModelTable(
            name='aktarunlog',
            table='akta_run_log',
        ),
    ]
