# Generated by Django 5.1.4 on 2025-03-05 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0012_alter_ufdfmetadata_system_void_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='cassette_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='diafiltration_volume_required',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='diavolumes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='final_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='final_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='flow_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='lmh_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='load_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='load_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='load_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='permeate_target_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='product_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='recovery',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='target_diafiltration_concentration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='target_flow_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='target_p2500_setpoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='target_p3000_setpoint',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='uf1_target_reservoir_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ufdfmetadata',
            name='yield_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
