# Generated by Django 5.1.4 on 2025-03-06 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0013_alter_ufdfmetadata_cassette_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VFMetadata',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('molecule_name', models.TextField()),
                ('experiment_name', models.TextField()),
                ('experimental_notes', models.TextField(blank=True, null=True)),
                ('filter_type', models.TextField(blank=True, null=True)),
                ('load_concentration', models.FloatField(blank=True, null=True)),
                ('load_volume', models.FloatField(blank=True, null=True)),
                ('load_mass', models.FloatField(blank=True, null=True)),
                ('target_pressure', models.FloatField(blank=True, null=True)),
                ('final_volume', models.FloatField(blank=True, null=True)),
                ('final_concentration', models.FloatField(blank=True, null=True)),
                ('product_mass', models.FloatField(blank=True, null=True)),
                ('yield_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vf_metadata',
            },
        ),
        migrations.CreateModel(
            name='VFTimeSeriesData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_step', models.BigIntegerField(blank=True, null=True)),
                ('batch_id', models.CharField(max_length=255)),
                ('pdat_time', models.DateTimeField()),
                ('process_time', models.FloatField(blank=True, null=True)),
                ('pir2600', models.FloatField(blank=True, null=True)),
                ('wir2700', models.FloatField(blank=True, null=True)),
                ('f_perm_value', models.FloatField(blank=True, null=True)),
                ('result_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.vfmetadata')),
            ],
            options={
                'db_table': 'vf_time_series_data',
                'managed': True,
            },
        ),
    ]
