# Generated by Django 5.1.4 on 2025-02-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0013_alter_aktafraction_table_alter_aktarunlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktachromatogram',
            name='uv_1_280',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktafraction',
            name='fraction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aktafraction',
            name='ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='downstream_step_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='method_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='run_log_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='run_on_system',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='run_type',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='sample_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='scouting_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='scouting_run_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='source_material_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='text_instruction_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktaresult',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aktarunlog',
            name='log_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktarunlog',
            name='ml',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
