# Generated by Django 5.1.4 on 2025-02-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0014_alter_aktachromatogram_uv_1_280_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AktaResult',
        ),
    ]
