# Generated by Django 5.1.4 on 2025-02-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0015_delete_aktaresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktaResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.CharField(max_length=50, unique=True)),
                ('column_name', models.TextField(blank=True, null=True)),
                ('column_volume', models.TextField(blank=True, null=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_id', models.CharField(blank=True, max_length=255, null=True)),
                ('run_type', models.BigIntegerField(blank=True, null=True)),
                ('scouting_id', models.BigIntegerField(blank=True, null=True)),
                ('scouting_run_num', models.BigIntegerField(blank=True, null=True)),
                ('group_id', models.BigIntegerField(blank=True, null=True)),
                ('system', models.CharField(blank=True, max_length=255, null=True)),
                ('source_material_id', models.BigIntegerField(blank=True, null=True)),
                ('downstream_step_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'akta_result',
            },
        ),
    ]
