# Generated by Django 5.1.4 on 2025-03-08 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0016_vfmetadata_vftimeseriesdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemetadata',
            name='sample_type',
        ),
    ]
