# Generated by Django 5.1.4 on 2025-03-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0017_remove_samplemetadata_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemetadata',
            name='sample_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
