# Generated by Django 5.1.4 on 2025-03-08 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0018_samplemetadata_sample_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemetadata',
            name='sample_type',
        ),
    ]
