# Generated by Django 5.1.4 on 2025-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0020_samplemetadata_analysis_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='analysis_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
