# Generated by Django 5.1.4 on 2025-03-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0021_alter_report_analysis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemetadata',
            name='dilution',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
