# Generated by Django 5.1.4 on 2025-03-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0022_samplemetadata_dilution'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
