# Generated by Django 5.1.4 on 2025-03-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0023_report_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='peakresults',
            name='system_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
