# Generated by Django 5.1.4 on 2025-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0024_peakresults_system_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaFlex2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('sample_id', models.CharField(max_length=255)),
                ('sample_type', models.CharField(max_length=255)),
                ('gln', models.FloatField()),
                ('glu', models.FloatField()),
                ('gluc', models.FloatField()),
                ('lac', models.FloatField()),
                ('nh4', models.FloatField()),
                ('pH', models.FloatField()),
                ('po2', models.FloatField()),
                ('pco2', models.FloatField()),
                ('osm', models.FloatField()),
            ],
            options={
                'db_table': 'nova_flex_2',
            },
        ),
    ]
