# Generated by Django 5.1.4 on 2025-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0025_novaflex2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaflex2',
            name='gln',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='glu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='gluc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='lac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='nh4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='osm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='pH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='pco2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novaflex2',
            name='po2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
