# Generated by Django 5.1.4 on 2025-03-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0027_alter_novaflex2_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novaflex2',
            name='sample_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
