# Generated by Django 5.1.4 on 2025-03-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0028_alter_novaflex2_sample_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovaReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('selected_result_ids', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'nova_report',
            },
        ),
    ]
