# Generated by Django 5.1.4 on 2025-03-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0030_novaflex2_day_novaflex2_experiment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViCellData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_id', models.CharField(max_length=100, unique=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('reactor_type', models.CharField(blank=True, max_length=10, null=True)),
                ('reactor_number', models.IntegerField(blank=True, null=True)),
                ('special', models.CharField(blank=True, max_length=50, null=True)),
                ('cell_count', models.FloatField(blank=True, null=True)),
                ('viable_cells', models.FloatField(blank=True, null=True)),
                ('total_cells_per_ml', models.FloatField(blank=True, null=True)),
                ('viable_cells_per_ml', models.FloatField(blank=True, null=True)),
                ('viability', models.FloatField(blank=True, null=True)),
                ('average_diameter', models.FloatField(blank=True, null=True)),
                ('average_viable_diameter', models.FloatField(blank=True, null=True)),
                ('average_circularity', models.FloatField(blank=True, null=True)),
                ('average_viable_circularity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vicell_data',
                'unique_together': {('date_time', 'sample_id')},
            },
        ),
    ]
