# Generated by Django 5.1.4 on 2025-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0031_vicelldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='vicelldata',
            name='sample_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
