# Generated by Django 5.1.4 on 2025-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0033_vicellreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktachromatogram',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktafraction',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktarunlog',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
