# Generated by Django 5.1.4 on 2025-04-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0034_aktachromatogram_date_time_aktafraction_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktachromatogram',
            name='ml',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
