# Generated by Django 5.1.4 on 2025-04-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0038_aktanodeids_id_alter_aktanodeids_result_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AktaNodeIds',
        ),
    ]
