# Generated by Django 5.1.4 on 2025-04-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0040_aktanodeids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktanodeids',
            name='conc_b',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='cond',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='deltac_pressure',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='fraction',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='ph',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='postc_pressure',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='prec_pressure',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='run_log',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='sample_flow',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='sample_pressure',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='system_flow',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='system_pressure',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='uv_1',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='uv_2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='aktanodeids',
            name='uv_3',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
