# Generated by Django 5.1.4 on 2025-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0043_alter_aktanodeids_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktaresult',
            name='report_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
