# Generated by Django 5.1.4 on 2025-04-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0044_aktaresult_report_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedGlycanComponents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_id', models.CharField(blank=True, max_length=255, null=True)),
                ('component_name', models.CharField(max_length=255, null=True)),
                ('observed_rt_min', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percent_amount', models.FloatField(blank=True, null=True)),
                ('expected_glycan_units', models.FloatField(blank=True, null=True)),
                ('glycan_units', models.FloatField(blank=True, null=True)),
                ('expected_mass_da', models.FloatField(blank=True, null=True)),
                ('observed_mass_da', models.FloatField(blank=True, null=True)),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('response', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'released_glycan_component',
            },
        ),
    ]
