# Generated by Django 5.1.4 on 2025-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0046_releasedglycancomponents_result_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlycanReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.TextField()),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('selected_result_ids', models.TextField(help_text='Comma-separated list of ReleasedGlycanComponents.result_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'glycan_report',
            },
        ),
    ]
