# Generated by Django 5.1.4 on 2025-04-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0047_glycanreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedGlycanComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.TextField()),
                ('observed_rt_min', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percent_amount', models.FloatField(blank=True, null=True)),
                ('expected_glycan_units', models.FloatField(blank=True, null=True)),
                ('glycan_units', models.FloatField(blank=True, null=True)),
                ('expected_mass_da', models.FloatField(blank=True, null=True)),
                ('observed_mass_da', models.FloatField(blank=True, null=True)),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('response', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'released_glycan_components',
            },
        ),
        migrations.CreateModel(
            name='ReleasedGlycanResult',
            fields=[
                ('result_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('result_name', models.TextField()),
                ('project_id', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'released_glycan_result',
            },
        ),
        migrations.DeleteModel(
            name='ReleasedGlycanComponents',
        ),
        migrations.AddField(
            model_name='releasedglycancomponent',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glycans', to='plotly_integration.releasedglycanresult'),
        ),
    ]
