# Generated by Django 5.1.4 on 2025-04-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0048_releasedglycancomponent_releasedglycanresult_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='glycanreport',
            table='released_glycan_report',
        ),
    ]
