# Generated by Django 5.1.4 on 2025-04-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0049_alter_glycanreport_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReleasedGlycanComponent',
            new_name='ReleasedGlycanComponents',
        ),
    ]
