# Generated by Django 5.1.4 on 2025-04-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0050_rename_releasedglycancomponent_releasedglycancomponents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlycanReport',
        ),
        migrations.DeleteModel(
            name='ReleasedGlycanComponents',
        ),
        migrations.DeleteModel(
            name='ReleasedGlycanResult',
        ),
    ]
