# Generated by Django 5.1.4 on 2025-04-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0051_delete_glycanreport_delete_releasedglycancomponents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlycanReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('selected_result_ids', models.TextField(help_text='Comma-separated UUIDs of ReleasedGlycanResult')),
                ('selected_glycan_names', models.TextField(help_text='Optional: comma-separated component_name values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'released_glycan_report',
            },
        ),
        migrations.CreateModel(
            name='ReleasedGlycanResult',
            fields=[
                ('result_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('result_name', models.TextField()),
                ('project_id', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'released_glycan_result',
            },
        ),
        migrations.CreateModel(
            name='ReleasedGlycanComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.TextField()),
                ('observed_rt_min', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('percent_amount', models.FloatField(blank=True, null=True)),
                ('expected_glycan_units', models.FloatField(blank=True, null=True)),
                ('glycan_units', models.FloatField(blank=True, null=True)),
                ('expected_mass_da', models.FloatField(blank=True, null=True)),
                ('observed_mass_da', models.FloatField(blank=True, null=True)),
                ('charge', models.IntegerField(blank=True, null=True)),
                ('response', models.FloatField(blank=True, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glycans', to='plotly_integration.releasedglycanresult')),
            ],
            options={
                'db_table': 'released_glycan_component',
            },
        ),
    ]
