# Generated by Django 5.1.4 on 2025-04-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0052_glycanreport_releasedglycanresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='glycanreport',
            name='department',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glycanreport',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
