# Generated by Django 5.1.4 on 2025-04-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0054_masscheckreport_masscheckresult_masscheckcomponent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AktaNodeIds',
        ),
    ]
