# Generated by Django 5.1.4 on 2025-04-17 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0055_delete_aktanodeids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AktaNodeIds',
            fields=[
                ('result_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('run_log', models.CharField(blank=True, max_length=1024, null=True)),
                ('fraction', models.CharField(blank=True, max_length=1024, null=True)),
                ('uv_1', models.CharField(blank=True, max_length=1024, null=True)),
                ('uv_2', models.CharField(blank=True, max_length=1024, null=True)),
                ('uv_3', models.CharField(blank=True, max_length=1024, null=True)),
                ('cond', models.CharField(blank=True, max_length=1024, null=True)),
                ('conc_b', models.CharField(blank=True, max_length=1024, null=True)),
                ('ph', models.CharField(blank=True, max_length=1024, null=True)),
                ('system_flow', models.CharField(blank=True, max_length=1024, null=True)),
                ('system_pressure', models.CharField(blank=True, max_length=1024, null=True)),
                ('sample_flow', models.CharField(blank=True, max_length=1024, null=True)),
                ('sample_pressure', models.CharField(blank=True, max_length=1024, null=True)),
                ('prec_pressure', models.CharField(blank=True, max_length=1024, null=True)),
                ('deltac_pressure', models.CharField(blank=True, max_length=1024, null=True)),
                ('postc_pressure', models.CharField(blank=True, max_length=1024, null=True)),
                ('imported', models.BooleanField(default=False)),
                ('timestamp_collected', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'akta_node_ids',
            },
        ),
    ]
