# Generated by Django 5.1.4 on 2025-04-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0059_cesdsmetadata_cesdstimeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CESDSReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('selected_samples', models.TextField()),
                ('selected_result_ids', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ce_sds_report',
            },
        ),
    ]
