# Generated by Django 5.1.4 on 2025-05-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0062_cesdsmetadata_cesdsreport_cesdstimeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesdsmetadata',
            name='sample_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
