# Generated by Django 5.1.4 on 2025-05-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0065_cesdsmetadata_cesdsreport_cesdstimeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIEFMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file_name', models.CharField(max_length=255)),
                ('sample_type', models.IntegerField(blank=True, null=True)),
                ('sample_id_full', models.CharField(max_length=255)),
                ('sample_id_clean', models.CharField(max_length=255)),
                ('sample_prefix', models.CharField(max_length=10)),
                ('data_file_path', models.TextField()),
                ('method_path', models.TextField()),
                ('user_name', models.CharField(max_length=255)),
                ('acquisition_datetime', models.DateTimeField(blank=True, null=True)),
                ('sampling_rate', models.FloatField()),
                ('total_data_points', models.IntegerField()),
                ('x_axis_title', models.CharField(max_length=255)),
                ('y_axis_title', models.CharField(max_length=255)),
                ('x_axis_multiplier', models.FloatField()),
                ('y_axis_multiplier', models.FloatField()),
                ('sample_set_name', models.CharField(max_length=255)),
                ('sample_set_id', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cief_metadata',
            },
        ),
        migrations.CreateModel(
            name='CIEFReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('selected_samples', models.TextField()),
                ('selected_result_ids', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cief_report',
            },
        ),
        migrations.CreateModel(
            name='CIEFTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_min', models.FloatField()),
                ('channel_1', models.FloatField()),
                ('channel_2', models.FloatField()),
                ('channel_3', models.FloatField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='plotly_integration.ciefmetadata')),
            ],
            options={
                'db_table': 'cief_time_series',
            },
        ),
    ]
