# Generated by Django 5.1.4 on 2025-05-21 18:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0066_ciefmetadata_ciefreport_cieftimeseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsSampleAnalysis',
            fields=[
                ('sample_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sample_date', models.DateField()),
                ('project_id', models.CharField(max_length=100)),
                ('run_date', models.DateField()),
                ('analyst', models.CharField(max_length=100)),
                ('a280_result', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_sample_analysis',
            },
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='buffers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='column_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='description_of_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='dn_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='load_cond',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='load_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='load_titer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='load_volume_ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='study_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='suggested_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aktaresult',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='LimsCeSdsResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('purity', models.FloatField()),
                ('band_pattern', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_ce_sds_result',
            },
        ),
        migrations.CreateModel(
            name='LimsCiefResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('main_peak', models.FloatField()),
                ('acidic_variants', models.FloatField()),
                ('basic_variants', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_cief_result',
            },
        ),
        migrations.CreateModel(
            name='LimsHcpResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('hcp_level', models.FloatField()),
                ('unit', models.CharField(default='ng/mg', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_hcp_result',
            },
        ),
        migrations.CreateModel(
            name='LimsMassCheckResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('expected_mass', models.FloatField()),
                ('observed_mass', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_mass_check_result',
            },
        ),
        migrations.CreateModel(
            name='LimsProaResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('proa_level', models.FloatField()),
                ('unit', models.CharField(default='ng/mg', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_proa_result',
            },
        ),
        migrations.CreateModel(
            name='LimsReleasedGlycanResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('glycan_profile', models.JSONField()),
                ('major_species', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_released_glycan_result',
            },
        ),
        migrations.CreateModel(
            name='LimsSecResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('main_peak', models.FloatField()),
                ('hmw', models.FloatField()),
                ('lmw', models.FloatField()),
                ('peak_data', models.JSONField(blank=True, null=True)),
                ('qc_pass', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_sec_result',
            },
        ),
        migrations.CreateModel(
            name='LimsTiterResult',
            fields=[
                ('sample_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='plotly_integration.limssampleanalysis')),
                ('titer', models.FloatField(blank=True, null=True)),
                ('qc_pass', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('review', 'Under Review')], default='in_progress', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lims_titer_result',
            },
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='ce_sds_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limscesdsresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='cief_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limsciefresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='hcp_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limshcpresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='mass_check_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limsmasscheckresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='proa_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limsproaresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='glycan_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limsreleasedglycanresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='sec_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limssecresult'),
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='titer_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.limstiterresult'),
        ),
    ]
