# Generated by Django 5.1.4 on 2025-05-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0067_limssampleanalysis_aktaresult_buffers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDSamples',
            new_name='LimsPDSamples',
        ),
        migrations.DeleteModel(
            name='DnAssignment',
        ),
        migrations.AlterModelTable(
            name='limspdsamples',
            table='lims_pd_samples',
        ),
    ]
