# Generated by Django 5.1.4 on 2025-05-21 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0069_limsdnassignment_delete_limspdsamples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limsdnassignment',
            name='operator',
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dn_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='limsdnassignment',
            name='unit_operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
