# Generated by Django 5.1.4 on 2025-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0071_limssourcematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssampleanalysis',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='limssampleanalysis',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
