# Generated by Django 5.1.4 on 2025-05-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0072_limssampleanalysis_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limssampleanalysis',
            name='run_date',
        ),
    ]
