# Generated by Django 5.1.4 on 2025-05-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0073_remove_limssampleanalysis_run_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limssampleanalysis',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
