# Generated by Django 5.1.4 on 2025-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0074_alter_limssampleanalysis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limssampleanalysis',
            name='sample_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
