# Generated by Django 5.1.4 on 2025-05-23 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0075_alter_limssampleanalysis_sample_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssampleanalysis',
            name='dn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='plotly_integration.limsdnassignment'),
        ),
    ]
