# Generated by Django 5.1.4 on 2025-05-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0076_limssampleanalysis_dn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limsdnassignment',
            name='dn',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
