# Generated by Django 5.1.4 on 2025-05-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0077_alter_limsdnassignment_dn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limssampleanalysis',
            name='dn',
        ),
    ]
