# Generated by Django 5.1.4 on 2025-05-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0078_remove_limssampleanalysis_dn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limsdnassignment',
            name='id',
        ),
        migrations.AlterField(
            model_name='limsdnassignment',
            name='dn',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
