# Generated by Django 5.1.4 on 2025-05-24 05:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0079_remove_limsdnassignment_id_alter_limsdnassignment_dn'),
    ]

    operations = [

        # migrations.AddField(
        #     model_name='limsdnassignment',
        #     name='source_material',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_dn_assignments', to='plotly_integration.limssourcematerial'),
        # ),
        # migrations.AddField(
        #     model_name='limssampleanalysis',
        #     name='dn',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='plotly_integration.limsdnassignment'),
        # ),
        # migrations.AddField(
        #     model_name='limssourcematerial',
        #     name='name',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='limssourcematerial',
        #     name='sm_id',
        #     field=models.BigIntegerField(default=django.utils.timezone.now, unique=True),
        #     preserve_default=False,
        # ),
    ]
