# Generated by Django 5.1.4 on 2025-05-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0080_remove_limssourcematerial_acid_addition_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='limssourcematerial',
            name='sm_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LimsSourceMaterialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('process', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.limssourcematerial')),
            ],
        ),
    ]
