# Generated by Django 5.1.4 on 2025-05-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0081_remove_limssourcematerial_acid_addition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limssourcematerialstep',
            name='source_material',
        ),
        migrations.AddField(
            model_name='limssampleanalysis',
            name='dn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='plotly_integration.limsdnassignment'),
        ),
        migrations.DeleteModel(
            name='LimsSourceMaterial',
        ),
        migrations.DeleteModel(
            name='LimsSourceMaterialStep',
        ),
    ]
