# Generated by Django 5.1.4 on 2025-05-24 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0082_remove_limssourcematerialstep_source_material_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsSourceMaterial',
            fields=[
                ('sm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_description', models.TextField(blank=True)),
                ('source_volume', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('final_conductivity', models.FloatField(blank=True, null=True)),
                ('final_pH', models.FloatField(blank=True, null=True)),
                ('final_concentration', models.FloatField(blank=True, null=True)),
                ('final_total_volume', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_source_materials', to=settings.AUTH_USER_MODEL)),
                ('resulting_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_material_record', to='plotly_integration.limssampleanalysis')),
                ('samples', models.ManyToManyField(related_name='used_in_source_materials', to='plotly_integration.limssampleanalysis')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_source_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lims_source_material',
            },
        ),
        migrations.CreateModel(
            name='LimsSourceMaterialStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('process', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('source_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.limssourcematerial')),
            ],
            options={
                'db_table': 'lims_source_material_step',
            },
        ),
    ]
