# Generated by Django 5.1.4 on 2025-05-24 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0083_limssourcematerial_limssourcematerialstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsdnassignment',
            name='source_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_dn_assignments', to='plotly_integration.limssourcematerial'),
        ),
    ]
