# Generated by Django 5.1.4 on 2025-05-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0084_limsdnassignment_source_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limssourcematerial',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limssourcematerial',
            name='source_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
