# Generated by Django 5.1.4 on 2025-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0085_alter_limssourcematerial_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssourcematerial',
            name='project_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
