# Generated by Django 5.1.4 on 2025-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0086_limssourcematerial_project_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectID',
            new_name='LimsProjectID',
        ),
        migrations.AlterModelTable(
            name='limsprojectid',
            table='lims_project_id',
        ),
    ]
