# Generated by Django 5.1.4 on 2025-05-28 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0087_rename_projectid_limsprojectid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimsProjectID',
            new_name='LimsFedBatchSamples',
        ),
        migrations.AlterModelTable(
            name='limsfedbatchsamples',
            table='lims_fed_batch_samples',
        ),
    ]
