# Generated by Django 5.1.4 on 2025-05-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0088_rename_limsprojectid_limsfedbatchsamples_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectInformation',
            new_name='LimsProjectInformation',
        ),
        migrations.AlterModelTable(
            name='limsprojectinformation',
            table='lims_project_information',
        ),
    ]
