# Generated by Django 5.1.4 on 2025-05-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0089_rename_projectinformation_limsprojectinformation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsUpstreamSamples',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sample_type', models.IntegerField(choices=[(1, 'UP'), (2, 'FB')])),
                ('sample_number', models.IntegerField()),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('sip_number', models.CharField(blank=True, max_length=255, null=True)),
                ('cell_line', models.CharField(blank=True, max_length=255, null=True)),
                ('experiment_number', models.IntegerField(blank=True, null=True)),
                ('culture_duration', models.IntegerField(blank=True, null=True)),
                ('vessel_type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('analyst', models.CharField(blank=True, max_length=255, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('unifi_number', models.CharField(blank=True, max_length=255, null=True)),
                ('titer_comment', models.TextField(blank=True, null=True)),
                ('cld_30ml_octet_titer', models.FloatField(blank=True, null=True)),
                ('pro_aqa_titer', models.FloatField(blank=True, null=True)),
                ('fast_pro_a_recovery', models.FloatField(blank=True, null=True)),
                ('purification_recovery_a280', models.FloatField(blank=True, null=True)),
                ('proa_eluate_a280_conc', models.FloatField(blank=True, null=True)),
                ('proa_eluate_volume', models.FloatField(blank=True, null=True)),
                ('hccf_loading_volume', models.FloatField(blank=True, null=True)),
                ('proa_recovery', models.FloatField(blank=True, null=True)),
                ('proa_column_size', models.FloatField(blank=True, null=True)),
                ('column_id', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('sec_2_wks_a_conc', models.FloatField(blank=True, null=True)),
                ('sec_2wks_n_conc', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lims_upstream_samples',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='LimsFedBatchSamples',
        ),
    ]
