# Generated by Django 5.1.4 on 2025-05-29 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0091_rename_cld_30ml_octet_titer_limsupstreamsamples_hf_octet_titer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limsupstreamsamples',
            old_name='description',
            new_name='development_stage',
        ),
    ]
