# Generated by Django 5.1.4 on 2025-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0092_rename_description_limsupstreamsamples_development_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsupstreamsamples',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
