# Generated by Django 5.1.4 on 2025-06-02 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0093_limsupstreamsamples_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssampleanalysis',
            name='up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_analysis', to='plotly_integration.limsupstreamsamples'),
        ),
    ]
