# Generated by Django 5.1.4 on 2025-06-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0094_limssampleanalysis_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssampleanalysis',
            name='sample_type',
            field=models.IntegerField(choices=[(1, 'UP'), (2, 'FB'), (3, 'PD')], default=4),
            preserve_default=False,
        ),
    ]
