# Generated by Django 5.1.4 on 2025-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0095_limssampleanalysis_sample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='limsdnassignment',
            name='scouting_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
