# Generated by Django 5.1.4 on 2025-06-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0096_limsdnassignment_scouting_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='plot_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
