# Generated by Django 5.1.4 on 2025-06-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0097_report_plot_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='limssecresult',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plotly_integration.report'),
        ),
    ]
