# Generated by Django 5.1.4 on 2025-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0098_limssecresult_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limssecresult',
            name='hmw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limssecresult',
            name='lmw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='limssecresult',
            name='main_peak',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
