# Generated by Django 5.1.4 on 2025-06-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0099_alter_limssecresult_hmw_alter_limssecresult_lmw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimsSampleSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.CharField(max_length=200, unique=True)),
                ('project_id', models.CharField(max_length=100)),
                ('sip_number', models.CharField(blank=True, max_length=50, null=True)),
                ('development_stage', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'lims_sample_sets',
                'managed': True,
                'unique_together': {('project_id', 'sip_number', 'development_stage')},
            },
        ),
        migrations.CreateModel(
            name='LimsAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('requested_by', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(default=1)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sample_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_requests', to='plotly_integration.limssampleset')),
            ],
            options={
                'db_table': 'lims_analysis_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LimsSampleSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plotly_integration.limssampleanalysis')),
                ('sample_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='plotly_integration.limssampleset')),
            ],
            options={
                'db_table': 'lims_sample_set_membership',
                'managed': True,
                'unique_together': {('sample_set', 'sample')},
            },
        ),
    ]
