# Generated by Django 5.1.4 on 2025-02-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0002_alter_samplemetadata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='date_acquired',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='samplemetadata',
            unique_together={('result_id', 'system_name')},
        ),
    ]
