# Generated by Django 5.1.4 on 2025-02-13 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotly_integration', '0003_alter_samplemetadata_date_acquired_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True},
        ),
    ]
